### ISSUE TITLE
Configuration in two neon files

### ISSUE THREAD

**Issue by FVesely** [nette/database#223]
Version: 3.0.1

### Bug Description
If I split configuration into two neon files I get exception Unexpected option 'database › options › lazy'

### Steps To Reproduce
First neon file
```
database:
  options:
    lazy: true
```
Second neon file
```
database:
  dsn: ''
  user: ''
  password: ''
```
### Expected Behavior
No exception. Works in version 2.4.8
